import React from "react";
import Accordion from "../Components/Accordion";

const Anecdotes = () => {
    return(
        <section className="Anecdotes">
            <section className="Intro">
                <p>Although the purpose of this README document is to provide an objective, unbiased introduction and overview of the major, we also thought it would be beneficial for students, especially underclassmen, to get personal insights from current CS majors of different grades. Note that these perspectives were provided by volunteers who wanted to contribute to the README so the contributors consisted of self-selected individuals, and therefore these testimonials may not be fully representative of the CS population at Cornell. Also note that these testimonials were collected from underclassmen (freshmen & sophomores) due to our target audience. However, we hope that these shared experiences can help shed light on what being a CS major could potentially be like in the Cornell community.</p>
            </section>
            <section className="Content">
                <Accordion
                    title="Freshman A"
                    content="I was drawn to computer science in high school when I learned Java by watching online videos and C by solving problems in a programming book. So I entered college knowing clearly that I would pursue a major in CS.
                    <br></br>
                    With my AP credit I skipped the introductory CS course, and faced the hard decision of choosing between CS 2110 and CS 2112. I first read the ACSU README to have a general idea of the differences between the two courses in terms of course material and workload. Next, I contacted students who had already taken the courses for advice, and finally made up my mind to try CS 2112 because I wanted to challenge myself during my first semester of college and also to gain more experience in building and maintaining a large codebase.
                    <br></br>
                    Since I had added CS 2112 to my course list and knew that it would take up a large portion of my time, I decided not to take too many credits during my first semester. The other CS class that I took was CS 2800, which turned out to be a nice course to take together with CS 2112. 2112 was project-based, whereas 2800 was problem-set-based and basically involved writing mathematical proofs and solving problem sets. So this combination was a good one, as I could have a nice balance between writing code and solving problem sets. Besides, another advantage of taking them at the same time was that with those two taken, I could select CS classes more freely for my second semester, because CS 2800 teaches fundamental concepts in CS and thus is a prerequisite for many electives.
                    <br></br>
                    In terms of the learning experience, CS 2112 truly deserved its reputation as a hard class. The eight homework projects were challenging, especially the last four of them, which together constituted a large project of more than 10,000 lines of code. However, the professor and the teaching assistants were all extremely experienced and helpful, and I found that the homework helped me understand the class materials thoroughly. Taking 2112 was definitely rewarding, and with the experience of handling the heavy workload, I am more confident to face the challenges of future advanced CS courses. So if you don’t know whether CS 2110 or CS 2112 fits you better, try both during the first few weeks and see for yourself which one you can handle better. And a general rule of thumb is that when you are not sure whether a particular class is worth taking, or just want to know if you can handle the workload of the class, always feel free to ask someone who has already taken it for advice.
                    <br></br>
                    Finally, some suggestions: first of all, go to office hours! The people there are prepared to help you, and sometimes you may even find a better solution to a problem at hand by just talking to the teaching assistant. (Check out  Rubber duck debugging.) Additionally, look for various opportunities on campus for CS majors, such as teaching or research positions. For instance, if you feel you are doing pretty well in a class and hope to share your passion for the class and help other students, you can apply for a position as a teaching assistant. Lastly, join events held by CS-related student organizations such as ACSU and WICC! They frequently organize events such as guest lectures, the student-faculty luncheon, and at the end of the year, the CS formal."
                />
                 <Accordion
                    title="Freshman B"
                    content="Coming in, I was pretty certain I was going to stick with CS as a major and taking more classes helped me solidify that decision. However, I was interested in many other fields and was struggling to choose a double major/minor. As of now I'm leaning towards double majoring in Math and CS, which helped me decide to transfer to Arts and Sciences from Engineering because the Math major is not offered in the Engineering school. There's a lot of discussion about whether Arts or Engineering has a better environment for studying CS, but I personally thought being in Arts would be better in approaching the theoretical side of CS I want to explore.
                    <br></br>
                    As of adjusting into the CS classes at Cornell, my first CS class was CS 2112, and it was very challenging for me because I'm not a high caliber student and I didn't have any experience in CS except for my chill APCS class I took during high school. Sometime during the second assignment I panicked so hard I dropped the class and told my friend I'm going to give up my CS major and become an AEP major. Then I decided to sit in CS 2110 and realized that I was actually enjoying CS 2112 a lot, so I added the class back in and somehow survived through it. It was definitely painful at times, but I ended up meeting so many talented and motivated people in the class, and I learned so much from the class itself and the people around me. I would definitely recommend to incoming freshmen CS majors to challenge themselves and dive into as many meme-worthy/difficult classes or activities as possible.
                    <br></br>
                    Another thing I learned during freshman year was that lectures, office hours, and readings are actually pretty important. This applies to all classes but I think this is good to emphasize. In general, I'm excessively lazy and fairly unmotivated, and that accompanied by my poor time management skills resulted in me skipping hilarious amounts of lectures, doing readings and assignments half-heartedly, and not going to office hours for the past year. Habits are hard to throw away so it's probably going to be a while for me to stop doing this, but I genuinely wish that I realized earlier how important being an earnest student is, especially in CS.
                    <br></br>
                    Also, I was surprised to find how welcoming the CS community at Cornell was. There's a lot of diversity in our student population in comparison to other institutions, and I am always proud and happy to tell others that I am a CS major here. Although I have experienced only a year of Cornell so far, I haven't yet felt discriminated because of my gender as a female CS student, and I am grateful for the support for women in computing. Overall, I'm glad that I chose Cornell for studying CS and I hope my remaining years are as, or more, academically intriguing and challenging as my freshman year has been."
                />
                 <Accordion
                    title="Freshman C"
                    content="My first experience with CS at Cornell was the CS Placement Exam that places you out of Python. I was a student that came to Cornell with little CS experience but was set on the major just because I thought I wouldn’t like anything else. Fast forward and one year later, and my feelings are pretty much the same except that a bond of affection has replaced the indifference to CS (Stockholm syndrome at its finest).  Since I passed the exam, I ended up taking 2110 and 2800 my first semester, which are pretty much the bread and butter (or maybe the flour and the milk that you use to make the bread and butter) of your CS curriculum.  In retrospect, it really doesn’t matter if you take these first or second semester. If you do not take them the first semester, take the time to adjust to Cornell and focus on other things since you will still have the time to take the classes without a rush the next semester. If you do end up taking the classes, be sure to spend an adequate amount of time on them as the concepts never go away, and the effort you put into a class and the challenges you face can benefit you in the long run. Since I was still adjusting to Cornell during that timeframe, I did not understand the importance and the way prelims worked and how they affect your grades and therefore underperformed. I was then encouraged by my peers and closed out the semester with satisfactory results. What I learned the most out of that semester is that you should never be afraid to ask. Asking others for help, even professors, may seem scary at first but you soon come to realize that everyone who is around you wants you to succeed and is sometimes even willing to put in extra time to help. Even if you are starting a project the day it is due both professors and TA’s are still willing to help you learn, as long as you yourself are willing to put in the effort. What I want to pass down is that you should know (or at least think you know) what you want to get out of your first year. In order to know what you want, you have to know what is available. Therefore, don’t hesitate to find out, talk to people, go to events, and start building an answer to that question. Things are always easier when you have a realistic goal."
                />
                 <Accordion
                    title="Freshman D"
                    content="I remember debating whether to take CS 1110 or CS 2110 my first semester at Cornell. Since I was pretty set on majoring in CS, I went ahead and signed up for CS 2110 because I thought affiliating as soon as possible was my best option. In retrospect, this wasn't the smartest decision I made. Not only did it not help me affiliate sooner, but I also missed out on a chance to learn Python. This obviously doesn't apply to you if you've already mastered Python. If you, however, find yourself in a similar situation, just go ahead and take CS 1110.
                    <br></br>
                    Choose your CS partners wisely. Try to become partners with someone with good work ethic and communication skills. If you don't, you will spend countless nights of frustration and misery.
                    <br></br>
                    Join ACSU's mentorship program! My mentor told me about various opportunities available to freshmen and helped me decide which classes to take. It's also just nice to have someone older tell you about their experiences and perspectives.
                    <br></br>
                    Start assignments early. Go to office hours early. Study for prelims early. Procrastination is the cause of all bad GPAs. I thought I could pull off what I did in high school in college, but people here are way too smart for that.
                    <br></br>
                    I personally was very self-conscious about my lack of experience and didn't apply to the programs oriented to underclassmen. Nobody cares that you applied and got rejected, so just apply to everything.
                    <br></br>
                    My last advice is to make a lot of friends. Opportunities to make new friends dwindle as years go by, and you will regret it if you don't have friends. After all, CS is no fun if you don't have friends to complain about classes with."
                />
                 <Accordion
                    title="Sophomore A"
                    content="I decided to become a CS major my second semester freshman year, after I had taken 1110 and 2110 and loved it. Thus as a sophomore, I affiliated with the CS major. I handed in my affiliation form just before the summer, and was notified of acceptance at the start of my first semester sophomore year. Although it is not required that you affiliate with your major until the second semester of sophomore year, I felt it was convenient to affiliate early, as you will be able to get a CS advisor early on, and are allowed to pre-enroll in 4000 level classes that are open to CIS students only during pre-enroll.
                    <br></br>
                    As for classes taken, once 2110 and 2800 are out of the way in Freshman year, a variety of 3000 and 4000 level classes are open. As an elective, I took CS 4320 and the practicum, CS 4321. At first it was very intimidating to sit in a 4000 level class as a Sophomore, but after a while I realized that courses have prerequisites for a reason, and once you meet those, it does not matter which year you are in the course, as you will already have the prior knowledge necessary to succeed in the course. However, the workload for 3000 and 4000 level classes are considerably larger than what I had experienced in freshman year, which took some time to get used to. In my second semester I took CS 3152, Intro to Game Design, which turned out to have the largest workload in all my classes, but also one of my favorite classes at Cornell. It was an awesome and rewarding experience. Personally, I feel that sophomore year is a year to knock off some core classes such as CS 3110 and 3410/3420, but also take some time to explore the great variety of 4000 level electives out there.
                    <br></br>
                    I also took some time during sophomore year to explore TAing opportunities. I was a course consultant for both semesters, and found it very rewarding, because I get to help other students in their coursework, refresh my memory in the concepts that I might have forgotten from class, as well as learn how to explain my thoughts clearly to another person. I would highly recommend TAing some of your favorite classes if you like the class/professor, want to help others, or just want to make some money through this on-campus job.
                    <br></br>
                    Overall I find sophomore year a great year to explore opportunities, whether it is enrolling in some interesting 4000 level classes, diving into the internship search, trying out research, or TAing some classes to help your peers. It is your second year, when you are familiar with what Cornell has to offer, but do not have to worry about graduation yet. So make it count."
                />
                <Accordion
                    title="Sophomore B"
                    content="It is quite hard to isolate my sophomore CS life from all I have been through at Cornell. I came to Cornell with undecided major and was truly overwhelmed by how many options are out there when I was a freshman. Trying to explore as many subjects as possible in the first year, I had my first CS course, CS 1110, in the spring semester and officially considered CS as a potential major on my list.
                    <br></br>
                    Since I was quite determined to be an Economics major, Sophomore life for me was to explore more about CS, make sure if I’m truly interested (because CS is not easy!) and balance the courses between Econ and CS. After taking the courses needed to declare the major, 2110 and 2800, I affiliated the major at the end of the first semester. Although CS advisor would not be assigned until the summer, I still found it better to affiliate early because students in CS major could more easily get the 4000 level course in pre-enroll period. Because I made up my mind to become a CS major in Sophomore year and hadn’t taken a lot of courses before, I just stuck to the CS flowchart and took only one CS core class (CS 3410) in the spring semester. Trying to plan my courses for Economics and CS, I also feel it is wise to decide the majors as early as possible for students with double or triple majors. It helps a lot to reasonably schedule the courses for all majors and college requirements later and to discuss with advisors or other faculty about your questions for future.          
                    <br></br>
                    In general, I think sophomore year is for exploring and balancing. As an underclassman, I still had plenty of time to take courses I’m interested in, explore academic activities and college life, and prepare for junior and senior years. Also, don’t worry if you have any questions. There are always people willing to help."
                />
                <Accordion
                    title="Sophomore C"
                    content="I already knew I was going to major in CS by the time I was a sophomore, but I had no idea which concentration to focus on, what electives to take, when I was going to take what class... But if I had one piece of advice, I would say definitely affiliate early! You won't necessarily get an advisor earlier, but you'll get the whole affiliating paperwork over and done with before your sophomore year really hits you hard, and you will have a leg up during pre-enroll if you want to get higher-level CS electives. And what you put down on your checklist won't lock you into a certain external specialization or vector--you can change it later very easily.
                    <br></br>
                    Affiliating early also helps you get your priorities straight, whether you realize you want to knock out the rest of your college requirements, or if you want to start taking more advanced classes right away. It helped me solidify my strategy going into sophomore year: try to get just one CS core class done per semester so I could really do well in it, finish off most of my engineering requirements, and try a couple of higher-level CS electives. Easier said than done, and I ended up making my sophomore year far too heavy credit-wise such that I was drowning in coursework for most of the time. But the silver lining to that is that I get to have lighter course loads for my next two years!
                    <br></br>
                    I guess freshman year, for me, was more about diving into college life and acclimating to a new academic work ethic; sophomore year was more about finding what is good (and really, really bad) for work-life balance. I got a lot more involved with my community, but I was also better at managing my own schedule. The resources and networks at Cornell and within Cornell's CS department are super helpful for getting advice on pretty much anything, so make sure to take advantage of it!"
                />
                <Accordion
                    title="Sophomore D"
                    content="For me, the prospect of sophomore year was exciting because now that I had finished the basic intro courses in the CS major, I could take more advanced 3000-level courses as well as the entire range of 4000-level electives. I signed up a pretty heavy combination of CS core and elective classes, which was tough and kept me more busy than I ever was freshman year, especially since I had started interviewing with a few companies and needed time to prepare for that. It wasn’t all bad though, because I still enjoyed spending most of my time taking CS courses that I was interested in rather than college requirements I just had to get done with. Two important things I learned this year:
                    <br></br>
                    1) Electives (both CS and non-CS) can be really unpredictable -- there were some that sounded cool but ended up dull, and there were some that I took on a whim and ended up loving, so don’t be afraid to go out of your comfort zone and try something different
                    <br></br>
                    2) Definitely get out and get involved in activities outside of classes, but also realize that you can’t do everything. Sort out what you want to prioritize and balance accordingly so you don’t burn out."
                />
                <Accordion
                    title = "Sophomore E"
                    content = "I started out comparatively late in computer science (after Freshman year). During my sophomore year, I was hesitant in trying out things because I thought I wasn’t qualified to do them. I was also worried of me being “late” (after all, there are people in the CS department who start CS as early as elementary school). Now, though, I feel that no one really is “late” and all that matters is how much you do and how much you like what you are doing. If anyone is feeling “late” (I had a lot of friends who were in the same boat--one of my friends decided to major in CS in their junior year) rest assured that there is no such thing as “late.” Also, try to talk to as many people as possible and figure out what you need to do. Cool thing that happened to me--I talked to a random guy in my swimming class, and he turned out to be an intern at Microsoft. He told me what I needed to do and how to apply for internships (I didn’t even know how a career fair worked!). The CS community is very large and diverse, so you can always find someone to ask for help."
                />
                <Accordion
                    title = "Sophomore F"
                    content = "Transitioning into sophomore year as a computer science major is perhaps one of the greatest “power spikes” you will have in your four years at Cornell. As a sophomore who had completed his intro courses freshman year, I was able to begin diving into the upper level classes and figuring out for myself where my interests lie. It is also the perfect time to actually see what is ahead of you, in terms of classes to take in order to graduate and internship opportunities that arise because of your new standing and experience. Overall I believe that sophomore year is the time for you to experiment with the opportunities that Cornell gives you. I ended up TA’ing my first class sophomore year which showed me how much more there is to learning the material presented in class and it opened my eyes as to how it is like being on the other side of the table and how much our professors care about us as students. I also ended up taking a dance class which I would place outside of my comfort zone.  Therefore I recommend you take this time and really shaping your life beyond academics and the mentality you built freshman year. "
                />
                <Accordion
                    title="Junior A"
                    content="My junior year was a sharp contrast from my underclassmen years. Having completed a good chunk of the requirements for the College of Engineering and the Computer Science core, this was the first year when I started taking 4000-level CS courses that interested me. I found this to be true for a lot of my friends too. Some dedicated their whole semester to their external specializations and other requirements that they didn’t even take a single CS course for a semester. I also found myself much busier than previous years, mostly due to interviews. Unlike freshmen and sophomore years, I found that I got a lot more attention from companies due to my status as a junior. Thankfully, I had a light-enough coursework for me to interview with as many places as I could afford to. Outside of classes, it was also interesting being an upperclassmen rather than an underclassmen. I also found myself taking leadership roles in clubs and getting involved in other activities on-campus as the leader rather than the follower I was in my underclassmen years.
                    <br></br>
                    Based on this, these are my tips for a rising junior in Computer Science
                    <br></br>
                    <ol>
                    <li>Get involved in something outside of classes and interview!</li>
                    <li>When you interview with places, also look for what the companies have to offer you, and start figuring out which places appeal to you and which places do not; this will pay dividends and save you a lot of time when you start looking for full-time jobs</li>
                    <li>Challenge yourself with interesting CS electives, but don’t forget to diversify your schedule with classes from other disciplines as well!</li></ol>"
                />
                <Accordion
                    title="Junior B"
                    content="For me, junior year was all about really exploring the things I was interested in, but also giving myself breathing room to enjoy my experiences at Cornell. With a lot of my engineering college requirements and liberal studies electives out of the way, I was more free to choose specific CS electives. I also started taking up additional responsibilities outside of my normal coursework by becoming a TA and involving myself in my club activities more. Because of this, I feel that being a junior is all about finally striking a good balance between work and play, which is especially important since junior year is when you should definitely be considering post-college options: what kind of work environment you want, what kind of company culture you desire, where you want to move, etc.
                    <br></br>
                    A lot of other juniors will be interviewing for summer internships or research positions, so I found it a good idea to get some practice in before the recruiting season to stay on top of my game. However, it becomes really hard to not get down on yourself if you get rejected multiple times--and it’s times like those where you really have to take a step back and tell yourself you’re doing fine. You’re already at Cornell University and in a top CS program, so you’re already in a great position compared to thousands of other people! It’s all well and good to have a goal or dream position you aspire to, but not if you’re wrecking yourself to get there."
                />
                <Accordion
                    title="Junior C"
                    content="If freshman year was the NBA draft and sophomore year was the preseason, junior year is the regular season. You are given a much wider breadth of opportunities, and your choices matter all the more.
                    <br></br>
                    While some students know exactly what kind of field they want to enter as early as freshman year, I spent my junior year nailing down exactly what I wanted to do. Now that many of the core requirements were out of the way, I was able to explore classes as diverse as machine learning, operating systems, and programming logics. Just taking these at the same time helped me figure out how I really wanted to spend my time.
                    <br></br>
                    I found it very difficult to balance my heavy workload with the job/internship search. I advise you to study up on technical interviews as early as possible, and to brush up before the fall of Junior Year, when most companies are looking. It is definitely possible to find a job during the spring, but figuring out your summer plans early helps ease your second semester of the year.
                    <br></br>
                    As a junior, you might also find yourself entering leadership roles in the activities you pursue. You will find yourself experienced enough to make authoritative decisions but still young enough to join new groups and make impacts in those groups.
                    <br></br>
                    Junior year is also an appropriate time to figure out what you want do after your undergraduate education. It is a good idea to remind yourself of how close you are to fulfilling your graduation requirements, and whether you qualify for early graduation or a higher-education program. Don’t get stuck or caught up in being satisfied with a single goal. Understand you are nearing the end, but remember to be reasonably flexible with your plan."
                />
                <Accordion
                    title="Senior A"
                    content="By your senior year, one of your main worries will be what kind of career you want to pursue after graduation. What I’ve come to find out is that questions like these can never be answered in a short amount of time. Throughout your sophomore and junior year, you should always let this question sit in the back of your mind. Often times, it’s easy to get swept up with questions like “which company do smart people work for?” or “which route pays the most?” but in the end, a person’s career is his/her own personal journey. It will bring you happiness and satisfaction to decide to do you want to do based on your preferences alone.
                    <br></br>
                    This was something I didn’t learn until I was interviewing for company after company and I realized that I couldn’t even answer a simple question about why I wanted to work at a certain place. It was hard to be genuine when I had applied to the companies that my friends were applying to based on the reputations that my friends had told me. When it came down to making a decision, I was missing the conviction that this career path was what I had been working towards all along. The lesson I learned real late in the game is that to develop a real purpose of wanting to do something, you have to put your own time into doing your own thinking.
                    <br></br>
                    CS degree in particular has one of the highest variability in terms of what you can do, and it’s hard to find out what you like and dislike if you don’t try enough things. CS at Cornell has so many paths to offer, and it’s never too late to join a club. I encourage you to try out something you haven’t yet because, in the end, being conscious of your own motivations and goals while being open to trying out new things will go a long way in ultimately helping you define where you will take your career."
                />
                <Accordion
                    title="Senior B"
                    content="tl;dr – Appreciate the people around you.
                    <br></br>
                    I went into Cornell telling myself “don’t focus on the grades, just try your best” because “the journey is more important than the destination” :P right. I learned the hard way – the journey IS important, but quality is MUCH better than quantity of time spent studying. I focused so much on studying and improving my efficiency at studying that I really undervalued many other aspects at Cornell.
                    <br></br>
                    What’s my actual point?
                    <br></br>
                    Take a good look around you and appreciate the people you have the privilege of meeting. Sure, you won’t get along with everyone. Sure, when you work on a project and your partner seems hopelessly incompetent (they probably aren’t, you have no idea what’s going on in their life/what they’re going through!), you probably get a little annoyed. And sure, you might have a few housemate problems to work out.
                    <br></br>
                    Focus on what their strengths are.
                    <br></br>
                    It seems like a no brainer and cliché to focus on the positives and the strengths of people around you, but it’s really easy to focus on negatives, what needs to be done, what can be improved, etc. because let’s face it – we’re human!
                    <br></br>
                    I had the most fun at Cornell when I stopped to appreciate people for who they were instead of [constantly] fixating on apartment chores, interviews, prelims, and so on. I took classes in the Human Ecology, ILR, Arts and Sciences, and Engineering colleges my last semester and met a plethora of super diverse, interesting, and awesome people. Although many (including myself) may think that ILR is on the opposite spectrum of CS, I gained a completely different and valuable perspective by taking Intro to Conflict Resolution and Negotiation. I also had the privilege of studying with an ILR student in that class who made me realize that his approach to learning and synthesizing the class material was far superior to my diligent word-for-word note taking and regurgitation (although sometimes this style worked really well for me in other classes!). (*** Tangent: My favorite Cornell class – Human Bonding – was in the Human Ecology school. Yes, I was a CS major. ***)
                    <br></br>
                    My advice? Meet people inside AND outside your major/college, appreciate what they bring to the table, [study efficiently,] and enjoy the Cornell experience."
                />
            </section>
        </section>
    )
}

export default Anecdotes